### ISSUE TITLE
A query about timing

### ISSUE THREAD

**Issue by peterhinch** [vshymanskyy/aiodns#4]
The time calculations [here](https://github.com/vshymanskyy/aiodns/blob/51e8585880bf8a61ad44cea590787aa36f97b736/aiodns.py#L147) don't look quite right. The value `dt` is a time difference (delta) and is based on modular arithmetic. At some point it wraps round from a high value to a low one.

The `ticks_add` method (L158) normally takes an "absolute" `ticks` value and adds a delta, producing a target "absolute" `ticks` value. I'm not sure that calling it with two delta values produces a sensible result, calling into question the `<` operator in L147.

I'm not 100% sure of my facts here, but in my code I adopt the following rules:
1. Maintain a clear distinction between "absolute" ticks values and deltas.
2. Only use comparison operators on deltas e.g. `if ticks_diff(abs_ti, abs_t2) > 0:`.

**Comment by vshymanskyy** [comment]
I think using `ticks_diff` is fine. Here's the direct example [from documentation](https://docs.micropython.org/en/latest/library/time.html):

![image](https://github.com/user-attachments/assets/e6b0ca30-5d76-4da9-91d5-38217adbd43c)

In case of aiodns, `time.ticks_ms()` and `t` are absolute, `tout` is a delta which should be OK

**Comment by peterhinch** [comment]
Where I suspect there is a problem is here:
```py
tout = time.ticks_add(dt, 50)
```
`dt` is a delta (the result of `ticks_diff`). The docs for [ticks_add](https://docs.micropython.org/en/latest/library/time.html#time.ticks_add) state:
> ticks parameter must be a direct result of call to [ticks_ms()](https://docs.micropython.org/en/latest/library/time.html#time.ticks_ms), [ticks_us()](https://docs.micropython.org/en/latest/library/time.html#time.ticks_us), or [ticks_cpu()](https://docs.micropython.org/en/latest/library/time.html#time.ticks_cpu) functions...

The output of `ticks_add` is a `ticks` value, not a delta.

Given that both your args are deltas, and your intended result is a delta, I think it's OK to add them:
```py
tout = dt + 50
```

**Comment by vshymanskyy** [comment]
Nice catch!

Currently `getaddrinfo` early-exits, but I'm thinking to keep the query process running in the background until the true timeout is reached. This way, more results will be cached and available for the application to use.
The `getaddrinfo` will still early-exit on the first result, and the `+50ms` adjustment will probably be removed.
